# Generated by Django 2.2.7 on 2019-11-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='tweet_count',
        ),
    ]
